paths:
  data: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\PhD\\Data\\NIKON\\20250613_TrexCISD2\\Traces"
  results: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\PhD\\Data\\NIKON\\20250613_TrexCISD2\\Results\\Spontaneous"
constants:
  smoothing_constant: 3
  stdev_non-oscillating: 0.04
  peak_threshold: 0.1
  cut_off_percentage: 0.2
  osc_start_time: 0
  osc_end_time: 60
# write null if you want to execute the script for all data files in your path
filename: "KO_CISD2_1.nd2 - ratio.xlsx"
sheetname: "FF0_resp"
Genotype: "KO_CISD2"
ID: "20250613_KO_CISD2_1"
