paths:
  data: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\PhD\\Data\\Nikon\\20250612_stellate_FCCP\\Traces"
  rate: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\PhD\\Data\\Nikon\\20250612_stellate_FCCP\\Results\\FCCP"
constants:
  start_time: 224
  end_time: 254
  smoothing_constant: 3
filename: "A_1001.nd2 - ratio.xlsx"
sheetname: "FF0_resp"
