paths:
  data: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\PhD\\Data\\Nikon\\20260116_trexRyR2_CISD2_ermtCEPIA\\Traces"
  results: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\PhD\\Data\\Nikon\\20260116_trexRyR2_CISD2_ermtCEPIA\\Results\\erCEPIA"
constants:
  smoothing_constant: 4
  peak_threshold: 0.2
  basal_start_time: 600
  basal_end_time: 630
  baseline_start_time: 600
  baseline_end_time: 630
  osc_start_time: 10
  osc_end_time: 130
# write null if you want to execute the script for all data files in your path
filename: "CTRL_2.nd2 - C=1_F4.xlsx"
sheetname: "FF0_resp"
Genotype: "CTRL"
Dose: "1.5_mM_Ca2+"
ID: "20260116_CTRL_2"
erCEPIA: True
