paths:
  data: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\PhD\\Data\\NIKON\\20240706_CN_calibration\\Traces"
  calibrated: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\PhD\\Data\\NIKON\\20240706_CN_calibration\\Calibrated"
  plots: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\PhD\\Data\\NIKON\\20240706_CN_calibration\\Calibrated"
constants:
  min_start_time: 156
  min_end_time: 600
  max_start_time: 600
  max_end_time: 628
# write null if you want to execute the script for all data files in your path
filename: "WT_3.nd2 - C=0.xlsx"
